task: 'oe62'
seed: 1 
data:
    train_path: /mnt/mydir/oe62-data/total_energy_lincorr_pbe0/train/pbe0_train.mdb
    val_path: /mnt/mydir/oe62-data/total_energy_lincorr_pbe0/val/pbe0_val.mdb
    test_path: /mnt/mydir/oe62-data/total_energy_lincorr_pbe0/test/pbe0_test.mdb
    
    mean: 0.0036029790876720654
    std: 1.742015096746636
model:
    type: 'gemnet-t'

    use_pbc: False
    use_phi_module: True

    num_blocks: 3
    extensive: true
    cutoff: 6.0
    max_neighbors: 50
    direct_forces: false

    num_radial: 128
    rbf: 
      name: gaussian
    emb_size_rbf: 16
    envelope: 
      name: polynomial
      exponent: 5
    num_spherical: 7
    cbf: 
      name: spherical_harmonics
    emb_size_cbf: 16
    emb_size_trip: 64
    emb_size_bil_trip: 64

    emb_size_atom: 256
    emb_size_edge: 512
    num_elements: 83

    num_before_skip: 1
    num_after_skip: 2
    num_concat: 1
    num_atom: 3

    activation: silu
    output_init: HeOrthogonal

    scale_file: /mnt/mydir/scaling-factors-oe62/gemnet_baseline.json
training:
    predict_forces: False

    batch_size: 64
    epochs: 300
    lr: 0.0005
    weight_decay: 0.00001
    clipping: 999 # 10 
    warmup_epochs: 3

    early_stopping_patience: null
    early_stopping_delta: 0.001

    pde_lambda: 0.1
    net_charge_lambda: 0.0
    pde_warmup_epochs: 0
    k_eigenvalues: 5
logging:
    logger: wandb # basic or wandb
    project_name: phi-module
    run_name: gemnet-phi-oe62
    group: gemnet-oe62

    output_dir: /mnt/mydir/ 

    log_interval_steps: 500 # only for TerminalLogger

    checkpoints_path: /mnt/mydir/gemnet-oe62 