task: 'md22'
seed: 1 
data:
    molecule: stachyose
    npz_path: /mnt/mydir/MD22/

    mean: -1578838.9203
    std: 1.0 
model:
    type: 'visnet'

    use_phi_module: True

    lmax: 2 
    vecnorm_type: null
    trainable_vecnorm: False
    num_heads: 8
    num_layers: 9
    hidden_channels: 256 
    num_rbf: 32
    rbf_type: 'expnorm'
    trainable_rbf: False
    activation: 'silu'
    attn_activation: 'silu'
    max_z: 100
    cutoff: 5.0
    max_num_neighbors: 32 

    output_model: 'Scalar'

    reduce_op: 'add'
training:
    predict_forces: True
    energy_lambda: 0.01
    force_lambda: 0.95

    batch_size: 4
    epochs: 3000 
    lr: 0.0002 
    weight_decay: 0.0 
    clipping: 999999999 
    warmup_epochs: 3 

    early_stopping_patience: 600
    early_stopping_delta: 0.001

    pde_lambda: 0.01 # 0.001
    net_charge_lambda: 0.0001
    pde_warmup_epochs: 0
    k_eigenvalues: 9
logging:
    logger: wandb
    project_name: phi-module
    run_name: visnet-md22-(stachyose)-phi-module
    group: visnet-md22-(stachyose)

    output_dir: /mnt/mydir/ 

    log_interval_steps: 500

    checkpoints_path: /mnt/mydir/visnet-stachyose-phi-module

# Ac-Ala3-NHMe -620662.7117
# DHA -631480.1418
# stachyose -1578838.9203
# AT-AT -1154896.6603
# AT-AT-CG-CG -2329950.4156
# buckyball-catcher -2877475.2607
# dw_nanotube -7799787.2822